### ISSUE TITLE
Shard computation hardcoded

### ISSUE THREAD

**Issue by gfusee** [multiversx/mx-sdk-nestjs#136]
Hey! Regarding the `AddressUtils` class and especially the computeShard function: 

```ts
static computeShard(hexPubKey: string) {
    const numShards = 3;

    [...]
  }
```

The `numShards` variable should not be hardcoded since there is no reason that the network has exactly 3 shards (I'm thinking about local testnets or if a network increases its shards number)

Maybe we can imagine a parameter "numShards" to this function that allows users to change it? For example with the API service we will be able to query the proxy's `v1.0/network/config` endpoint to get the number of shards

**Comment by tanghel** [comment]
Makes sense. Fixed in https://github.com/multiversx/mx-sdk-nestjs/pull/137
